---
- include: deps.yml
- name: Copy thingsverse-agent
  copy:
    src=thingsverse-agent
    dest=/usr/local/src
    mode=u=rwx,g=rwx,o=rx
- name: Copy thingsverse-payload-parser
  copy:
    src=thingsverse-payload-parser
    dest=/usr/local/src
    mode=u=rwx,g=rwx,o=rx
- name: Run npm install
  command: npm install
    chdir=/usr/local/src/thingsverse-agent
    creates=/usr/local/src/thingsverse-agent/node_modules
- name: Install local modules
  command: npm install --save ../thingsverse-payload-parser
    chdir=/usr/local/src/thingsverse-mqtt
    creates=/usr/local/src/thingsverse-mqtt/node_modules/thingsverse-payload-parser