---
- include: deps.yml
- name: Copying thingsverse-web
  copy:
    src=thingsverse-web
    dest=/usr/local/src
    mode=u=rwx,g=rwx,o=rx
- name: Running npm install
  command: npm install
    chdir=/usr/local/src/thingsverse-web
    creates=/usr/local/src/thingsverse-web/node_modules
- name: Install systemd script
  copy:
    src=thingsverse-web.service
    dest=/lib/systemd/system
- name: Install nginx config
  copy:
    src=thingsverse-web.conf
    dest=/etc/nginx/sites-enabled
- name: Start thingsverse-web
  service:
    name=thingsverse-web
    state=restarted
    enabled=yes
- name: Restart nginx
  service:
    name=nginx
    state=reloaded